// SPDX-License-Identifier: Apache-2.0

export {
  ActiveRouteAttestationError,
  type ActiveRouteExpectation,
  type AttestConvergedActiveRouteOptions,
  attestConvergedActiveRoute,
  attestFleetRecordActiveRoute,
} from './active-route.js';
export {
  applicationBindingTopology,
  applicationR2Bindings,
  applicationSecretNames,
  applicationSecretValues,
  canonicalApplicationBindings,
  reserveApplicationR2Resources,
} from './application-bindings.js';
export {
  BACKEND_SWITCH_SUBPHASES,
  type BackendSwitchApplicationR2Progress,
  type BackendSwitchCandidateSnapshot,
  type BackendSwitchDecommissionRelease,
  type BackendSwitchDecommissionRouteTarget,
  type BackendSwitchDecommissionSnapshot,
  type BackendSwitchIntent,
  type BackendSwitchLease,
  type BackendSwitchMutationFence,
  type BackendSwitchProvider,
  type BackendSwitchSubphase,
  type BridgeMutationPlan,
  type BridgeSnapshot,
  decommissionBackendSwitch,
  type FinalizedOrdinaryStateProvider,
  finalizeBackendSwitch,
  type PlainBackendSnapshot,
  reconcileFinalizedBackendSwitchState,
  rollbackBackendSwitch,
  switchPlainDeploymentToWorkersForPlatforms,
} from './backend-switch.js';
export {
  CloudflareApiPlainWorkerBackend,
  type CloudflareApiPlainWorkerBackendOptions,
} from './cloudflare-api-plain-worker-backend.js';
export {
  type CloudflareClientOptions,
  CloudflarePlaneCapabilityError,
  CloudflareProvisioningClient,
  type ControlWorkerInspection,
  type ControlWorkerSpec,
  type DurableDatabaseExportStore,
  type OrdinaryWorkerFootprint,
  type PlainWorkerCloudflareClientOptions,
} from './cloudflare-client.js';
export {
  type CloudflareApiRateCoordinator,
  D1CloudflareApiRateCoordinator,
  type D1CloudflareApiRateCoordinatorOptions,
  ProcessLocalCloudflareApiRateCoordinator,
} from './cloudflare-rate-coordinator.js';
export { FileSystemDatabaseExportStore } from './export-store.js';
export {
  auditFleetDrift,
  type DriftFinding,
  type FleetVersionRow,
  fleetVersionReport,
  migrateFleet,
  rollbackExternalRelease,
} from './fleet.js';
export type { HostRoutingTarget } from './host-routing.js';
export {
  PlainWorkerBackend,
  type PlainWorkerBackendOptions,
} from './plain-worker-backend.js';
export {
  type PlatformPlaneClient,
  type PlatformPlaneResult,
  type PlatformPlaneSpec,
  type PlatformWorkerInspection,
  provisionPlatformPlane,
} from './platform-plane.js';
export {
  defaultDeploymentEgressPolicy,
  type ExternalResourceIdentity,
  externalEgressProxyScriptName,
  externalPlatformResourceGroupId,
  externalStateScriptName,
  trustedArtifactDigest,
  validateExternalPlatformProfile,
} from './platform-resources.js';
export {
  type CleanupDeploymentArtifactsOptions,
  cleanupDeploymentArtifacts,
  type DecommissionDeploymentOptions,
  decommissionDeployment,
  type ForceDecommissionDeploymentOptions,
  forceDecommissionDeployment,
  type ProvisionDeploymentOptions,
  ProvisioningError,
  provisionDeployment,
} from './provision.js';
export { generateDeploymentSecrets } from './secrets.js';
export { fleetSettlementKey } from './settlement.js';
export { deploymentSpecDigest } from './spec-digest.js';
export {
  D1FleetStateStore,
  type D1FleetStateStoreOptions,
  type FleetStateDatabase,
} from './state-store.js';
export {
  type ActiveRouteAttestation,
  type ApplicationBindingTopology,
  type ApplicationR2Binding,
  type ApplicationR2BucketSnapshot,
  type ApplicationR2Resource,
  type D1Migration,
  type DatabaseExport,
  type DatabaseReference,
  type DecommissionAdvanceIntent,
  type DecommissionAdvanceToken,
  type DecommissionAdvanceTokenClassification,
  type DecommissionAttachmentProgress,
  type DecommissionAttachmentPurpose,
  type DecommissionAttachmentScanEvidence,
  type DecommissionAttachmentScanInput,
  type DecommissionAttachmentScanResult,
  type DecommissionAuditEvent,
  type DecommissionAuditSink,
  type DecommissionBlockedAttachment,
  type DecommissionIntentCommon,
  type DecommissionOperationIdentity,
  type DecommissionOperationMode,
  type DecommissionRecordIdentity,
  type DecommissionResult,
  type DeploymentApplicationBindings,
  type DeploymentEgressPolicy,
  type DeploymentSecrets,
  type DeploymentSpec,
  type DurableObjectBindingInventory,
  type DurableObjectMigration,
  type ExternalMigrationIntent,
  type ExternalMigrationSubphase,
  type ExternalMutationFence,
  type ExternalPlatformProfile,
  type ExternalPlatformResources,
  type ExternalPlatformTargetDescription,
  type ExternalReleaseSnapshot,
  type ExternalReleaseTopology,
  type FleetInventoryDeployment,
  type FleetInventoryFinding,
  type FleetRecord,
  type FleetResourceInventory,
  type FleetSettlementContext,
  type FleetSettlementEntry,
  type FleetSettlementHost,
  type FleetStateLease,
  type FleetStateStore,
  type ForceDecommissionStep,
  type InitialExecutionFenceState,
  type LiveDeployment,
  type MaintenanceHealth,
  type NormalDecommissionLifecyclePhase,
  type ObservedActiveRoute,
  type PlainWorkerCleanupOutcome,
  type PlainWorkerCustomDomain,
  type PlainWorkerDatabaseExportResult,
  type PlainWorkerDatabaseInventoryEntry,
  type PlainWorkerDeploymentStatus,
  type PlainWorkerMutationOutcome,
  type PlainWorkerProvisioningApi,
  type PlainWorkerRouteApi,
  type PlainWorkerUploadIntent,
  type PlainWorkerUploadIntentBase,
  type PlainWorkerUploadOutcome,
  type PlainWorkerVersionBinding,
  type PlainWorkerVersionDetail,
  type PlainWorkerVersionSummary,
  type PlatformPlaneLease,
  type PlatformPlaneResourceSet,
  type PlatformPlaneStateStore,
  type PlatformResourceProvisioningResult,
  type PlatformWorkerSnapshot,
  PROVISIONING_PHASES,
  type PromotionGuard,
  type ProviderBindingIdentity,
  type ProvisioningBackend,
  type ProvisioningBackendKind,
  type ProvisioningPhase,
  type ProvisioningResult,
  type R2Jurisdiction,
  type ScriptInventoryTarget,
  type SeedDeploymentIdentityOptions,
  type TrustedWorkerArtifact,
  type WorkerModule,
  type WorkerZoneRoute,
} from './types.js';
export {
  deploymentKey,
  validateDeploymentSecrets,
  validateDeploymentSpec,
} from './validation.js';
export {
  deriveStateEgressCredential,
  externalReleaseScriptName,
  type WorkersForPlatformsApi,
  WorkersForPlatformsBackend,
} from './workers-for-platforms-backend.js';
export {
  type BackendSwitchApi,
  composeLegacyBridgeArtifact,
  LEGACY_APPLICATION_MODULE_PLACEHOLDER,
  type SwitchBridgeRemovalAuthority,
  WorkersForPlatformsBackendSwitchProvider,
  type WorkersForPlatformsBackendSwitchProviderOptions,
} from './workers-for-platforms-backend-switch-provider.js';
export { WranglerLoopBackend } from './wrangler-loop-backend.js';
export {
  type CommandResult,
  type CommandRunner,
  WranglerCommandRunner,
} from './wrangler-runner.js';
